### ISSUE TITLE
div II feedback

### ISSUE THREAD

**Issue by mariumtapal** [arrismo/criterioncollection#11]
looking at last commit [69ba934](https://github.com/arrismo/criterioncollection/commit/69ba9349f5e5f6fbd6cf0219b4a65bf125c5f9f4)

1. Passes `install_github`: ✅
2. Documentation builds: ✅
3. Passes R CMD check: ✅

`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`

@beanumber

**Comment by beanumber** [comment]
It looks like you have a lot of missing data in your table. I'd recommend getting all of those carriage returns out of your CSV file in the first place, especially if you are going to be editing it by hand.
