### ISSUE TITLE
div III feedback

### ISSUE THREAD

**Issue by mariumtapal** [arrismo/criterioncollection#13]
1. Passes `install_github`: ✅ 
2. Documentation builds: ✅
3. Passes R CMD check: ✅
`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`
4. Results of `devtools::test()`: ✅
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 8 ]

@beanumber

**Comment by beanumber** [comment]
- I think `boxsets` should contain an ID variable (I suppose `imdb_id`). Otherwise do you have to link them by name? 
- Why do the `find_by*()` function call `View()` and `print()` and return a value??? Just returning the data frame should be enough. 

Please see #14 for suggested improvements.
